server:
  port: 8081
  compression:
    enabled: true

spring:
  devtools:
    restart:
      enabled: false

  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/menuplus
    username: postgres
    password: 12345

  jpa:
    hibernate:
#      ddl-auto: validate
      ddl-auto: update # Uncomment this line to enable auto schema update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: localhost         # Địa chỉ Redis server
      port: 6379              # Cổng Redis server
      password:               # Nếu không có mật khẩu thì để trống hoặc bỏ dòng này
      database: 0             # Redis database index (thường dùng 0)
      timeout: 600000         # Timeout (ms), ở đây là 10 phút
      repositories:
        enabled: false

  jackson:
    serialization:
      write_dates_as_timestamps: false


auth:
  jwtSecret: ${MP_AUTH_JWT_SECRET:dkzxhoj8328ijqju3cam}
  jwtExpire: 864000000

springdoc:
  swagger-ui:
    enabled: true
